version: '3.8'

services:
  sentiment-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
